---
- name: Config Web VM with Docker
  hosts: webservers
  become: true
  tasks:

  - name: Remove Apache
    apt:
      name: apache2
      state: absent

  - name: docker.io
    apt:
      update_cache: yes
      name: docker.io
      state: present

  - name: Install pip3
    apt:
      name: python3-pip
      state: present
      force_apt_get: yes

  - name: Install Docker Python Module
    pip:
      name: docker
      state: present

  - name: Download and Launch a Docker Web Container
    docker_container:
      name: dvwa
      image: cyberxsecurity/dvwa
      state: started
      restart_policy: always
      published_ports: 80:80

  - name: Enabled Docker Service
    systemd:
      name: docker
      enabled: yes